"""Compatible ingestion exports; adapters, parsing and orchestration are separated."""
from .ingestion_types import (
    SourceIngestionResult,
    SourceFetchError,
    ArticleEnrichmentResult,
    SourceProbeResult,
    SUPPORTED_ACTIVE_SOURCE_TYPES,
    POSITIVE_CONTAINER_TERMS,
    NEGATIVE_CONTAINER_TERMS,
    BLOCKED_URL_SEGMENTS,
    PREFERRED_URL_SEGMENTS,
    LIVE_MATCH_TRACKER_TERMS,
    CHAMPIONAT_ALLOWED_TOP_LEVEL_SECTIONS,
    CHAMPIONAT_BLOCKED_TOP_LEVEL_SECTIONS,
    ARTICLE_CONTAINER_TERMS,
    ARTICLE_NEGATIVE_TERMS,
    ARTICLE_TRAILING_NOISE_MARKERS,
    HIGH_PRIORITY_TERMS,
    MEDIUM_PRIORITY_TERMS,
    MAJOR_EVENT_TERMS,
    OFFICIAL_SIGNAL_TERMS,
    DEFAULT_INGEST_MAX_ITEM_AGE,
)
from .ingestion_text import (
    _merge_tags,
    _is_usable_full_text,
    _is_probe_usable_full_text,
    _is_usable_lead,
    _looks_like_live_match_tracker,
    _should_drop_raw_item_as_service_page,
    _looks_like_story_title,
    _looks_like_listing_title,
    _looks_like_category_label,
    _normalize_whitespace,
    _split_meta_values,
    _looks_like_article_text_container,
    _normalize_article_text,
    _is_sovsport_preferred_article_container,
    _contains_article_noise_marker,
    _article_context_overlap,
    _score_article_text_candidate,
    _normalize_jsonld_article_body,
    _split_article_text,
    _dedupe_article_paragraphs,
    _trim_article_trailing_noise,
    _trim_article_trailing_noise_text,
    _normalize_dedupe_text,
    _text_overlap_ratio,
    _serialize_sitemap_payload,
    _xml_local_name,
    _find_child,
    _find_child_text,
    _extract_time_hint,
    _container_score,
    _article_container_score,
    _looks_like_listing_text,
    _looks_like_translit_slug_title,
    _try_parse_datetime,
    _node_text,
    _parse_datetime,
    _strip_html,
)
from .ingestion_collection import (
    ingest_sources,
    ingest_sources_with_results,
    _resolve_source_runtime,
    _select_effective_adapter,
    _select_effective_url,
    _capability_supports_adapter,
    raw_items_to_news,
    _collect_source_items_with_retry,
    _collect_source_items_via_ai_fallback,
    _collect_source_items,
)
from .ingestion_enrichment import (
    enrich_raw_item_content,
    _choose_best_local_partial_enrichment,
    _persist_raw_item_enrichment,
    _should_allow_web_search_fallback,
    _resolve_enriched_raw_headline,
)
from .ingestion_probing import (
    probe_source,
    probe_source_auto,
    _score_probe_result,
    _probe_support_flags,
    _build_auto_probe_candidates,
    _candidate_urls_for_news_sitemap,
    _candidate_urls_for_sitemap,
    _candidate_urls_for_rss,
    _host_specific_rss_candidates,
    _build_candidate_urls,
    _auto_probe_base_urls,
    _section_probe_path,
    _extract_sitemap_urls_from_robots,
    _extract_feed_links_from_html,
)
from .ingestion_feeds import (
    _parse_feed,
    _parse_rss,
    _parse_atom,
)
from .ingestion_sitemaps import (
    _parse_news_sitemap_source,
    _parse_sitemap_source,
    _parse_news_sitemap_document,
    _is_allowed_news_sitemap_article_url,
    _is_championat_source,
    _is_allowed_championat_news_url,
    _parse_generic_sitemap_document,
    _sorted_sitemapindex_children,
    _extract_sitemap_order_hint,
)
from .ingestion_scraping import (
    _parse_scraping_source,
    _parse_sovsport_articles_source,
    _parse_sovsport_news_source,
    _discover_ai_research_candidates_from_listing,
    _ScrapingCandidate,
    _ScrapingDocumentParser,
)
from .ingestion_ai_discovery import (
    _parse_ai_research_source,
    _serialize_ai_discovery_payload,
)
from .ingestion_article_extraction import (
    extract_article_enrichment,
    _extract_article_enrichment_from_html,
    _choose_best_article_full_text,
    extract_article_full_text,
)
from .ingestion_network import (
    fetch_remote_document,
    _fetch_remote_document,
)
from .ingestion_filtering import (
    _filter_new_items,
    _add_filter_reason,
    _filter_new_items_with_reasons,
    _items_look_descending_by_freshness,
)
from .ingestion_scoring import (
    _build_raw_item,
    _classify_category,
    _score_importance,
    build_importance_score_breakdown,
    _score_importance_components,
    _triage_label,
    _freshness_bonus,
    _source_reputation_bonus,
    _category_bonus,
)
from .ingestion_article_parser import (
    _ArticleDocumentParser,
    _merge_json_ld_article_metadata,
)
from .ingestion_urls import (
    _make_dedupe_key,
    _normalize_url,
    _normalize_candidate_url,
    _looks_like_scraping_article_url,
    _looks_like_generic_sitemap_article_url,
    _title_from_url,
    _is_sovsport_articles_source,
    _is_sovsport_news_source,
    _build_sovsport_news_article_url,
    _is_sovsport_host,
    _looks_like_news_url,
)

from .ingestion_types import CATEGORY_RULES, SOURCE_REPUTATION_HINTS
